name: Compile IP/ASN Lookup

on:
  schedule:
    - cron:  '0 0 1 * *' 

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: hadiasghari/pyasn
          path: pyasn

      - name: Download and convert IP/ASN files
        run: |
          pip install pyasn
          python3 pyasn/pyasn-utils/pyasn_util_download.py --latestv4
          python3 pyasn/pyasn-utils/pyasn_util_convert.py --single *.bz2 IPASN.txt
          python3 txt_to_json.py

      - name: Release IPASN.json
        run: |
          tag=$(date +%Y%m%d)
          gh release create --latest ${tag} IPASN.json || gh release upload --clobber ${tag} IPASN.json
        env:
            GH_REPO: ${{ github.repository }}
            GH_TOKEN: ${{ github.token }}
